# Generated by Django 4.0.4 on 2022-05-11 15:08

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('user_name', models.CharField(max_length=120, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='логин')),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='имя пользователя')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата регистрации')),
                ('image', models.ImageField(default='default_user_image/default_user_img.png', upload_to=users.models.slug_path, verbose_name='изображение')),
                ('gender', models.CharField(blank=True, choices=[('m', 'мужчина'), ('w', 'женщина')], max_length=30, null=True, verbose_name='пол')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('about', models.TextField(blank=True, null=True, verbose_name='о себе')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='страна')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', users.models.AccountManager()),
            ],
        ),
    ]
