# Generated by Django 4.0.4 on 2022-05-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'мужчина'), ('W', 'женщина'), ('NS', 'Не выбрано')], default='NS', max_length=30, verbose_name='пол'),
        ),
    ]
