# Generated by Django 4.0.4 on 2022-05-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина'), ('NS', 'Не выбрано')], default='NS', max_length=30, verbose_name='пол'),
        ),
    ]
