# Generated by Django 4.0.4 on 2022-05-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('NS', 'Не выбрано'), ('M', 'Мужчина'), ('W', 'Женщина')], default='NS', max_length=30, verbose_name='пол'),
        ),
    ]
