# Generated by Django 4.0.4 on 2022-05-23 15:55

from django.db import migrations, models
import users.models
import users.storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default_user_image/default_user_img.png', storage=users.storage.OverwriteStorage(), upload_to=users.models.slug_path, verbose_name='изображение'),
        ),
    ]
