# Generated by Django 4.0.4 on 2022-05-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, default='', verbose_name='о себе'),
            preserve_default=False,
        ),
    ]
