# Generated by Django 4.0.4 on 2022-06-05 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_connectionhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connectionhistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='connectionhistory',
            name='connections',
            field=models.IntegerField(default=0, verbose_name='кол-во соединений'),
        ),
        migrations.AlterField(
            model_name='connectionhistory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.RemoveField(
            model_name='connectionhistory',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='connectionhistory',
            name='status',
        ),
    ]
