# Generated by Django 4.0.4 on 2022-05-11 15:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeReadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=120, verbose_name='слаг')),
                ('image', models.ImageField(blank=True, null=True, upload_to=store.models.slug_path, verbose_name='изображение')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'возвраст читателя',
                'verbose_name_plural': 'возвраста читателя',
            },
        ),
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='имя')),
                ('slug', models.SlugField(max_length=120, verbose_name='слаг')),
                ('image', models.ImageField(default='default_author_image/default_author_img.png', upload_to=store.models.slug_path, verbose_name='изображение')),
                ('biograpy', models.TextField(verbose_name='биография')),
                ('centry_of_life', models.PositiveSmallIntegerField(verbose_name='век')),
                ('country', models.CharField(max_length=120, verbose_name='страна')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'авторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='название')),
                ('original_title', models.CharField(blank=True, max_length=120, null=True, verbose_name='оригинальное название')),
                ('slug', models.SlugField(max_length=120, verbose_name='слаг')),
                ('image', models.ImageField(default='default_book_image/default_book_img.png', upload_to=store.models.slug_path, verbose_name='изображение')),
                ('book_file', models.FileField(blank=True, null=True, upload_to=store.models.slug_file_path, verbose_name='файл')),
                ('description', models.TextField(max_length=512, verbose_name='описание')),
                ('full_description', models.TextField(blank=True, null=True, verbose_name='полное описание')),
                ('year', models.CharField(blank=True, max_length=30, null=True, verbose_name='время событий')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='кол-во страниц')),
                ('price', models.PositiveIntegerField(verbose_name='текущая цена')),
                ('old_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='старая цена')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата добавления')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги',
            },
        ),
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=120, verbose_name='слаг')),
                ('image', models.ImageField(default='default_collection_image/default_collection_img.jpg', upload_to=store.models.slug_path, verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'коллекция',
                'verbose_name_plural': 'коллекции',
            },
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=120, verbose_name='слаг')),
                ('image', models.ImageField(default='default_genre_image/default_genre_img.png', upload_to=store.models.slug_path, verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='LocationEventsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=120, verbose_name='слаг')),
                ('image', models.ImageField(blank=True, null=True, upload_to=store.models.slug_path, verbose_name='изображение')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'место действия',
                'verbose_name_plural': 'места действия',
            },
        ),
        migrations.CreateModel(
            name='SubCollectionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='название')),
                ('slug', models.SlugField(max_length=120, verbose_name='слаг')),
                ('image', models.ImageField(blank=True, null=True, upload_to=store.models.slug_path, verbose_name='изображение')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='описание')),
                ('collection', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.collectionmodel', verbose_name='коллекция')),
            ],
            options={
                'verbose_name': 'подколлекция',
                'verbose_name_plural': 'подколлекции',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата написания')),
                ('date_change', models.DateTimeField(blank=True, null=True, verbose_name='дата изменения')),
                ('is_delete', models.BooleanField(default=False, verbose_name='удален')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bookmodel', verbose_name='книга')),
                ('comment_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.commentmodel', verbose_name='на комментарий')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
