# Generated by Django 4.0.4 on 2022-05-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agereadmodel',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='collectionmodel',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='genremodel',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='locationeventsmodel',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='слаг'),
        ),
        migrations.AlterField(
            model_name='subcollectionsmodel',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='слаг'),
        ),
    ]
