# Generated by Django 4.0.4 on 2022-05-19 08:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_cartmodel_cart_rename_ordermodel_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_alter_agereadmodel_slug_alter_authormodel_slug_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgeReadModel',
            new_name='AgeRead',
        ),
        migrations.RenameModel(
            old_name='AuthorModel',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='BookModel',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='CollectionModel',
            new_name='Collection',
        ),
        migrations.RenameModel(
            old_name='CommentModel',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='GenreModel',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='LocationEventsModel',
            new_name='LocationEvents',
        ),
        migrations.RenameModel(
            old_name='SubCollectionsModel',
            new_name='SubCollections',
        ),
    ]
