# Generated by Django 4.0.4 on 2022-05-23 16:51

from django.db import migrations, models
import store.models
import store.storage


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_agereadmodel_ageread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ageread',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=store.storage.OverwriteStorage(), upload_to=store.models.slug_path, verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default_book_image/default_book_img.png', storage=store.storage.OverwriteStorage(), upload_to=store.models.slug_path, verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(default='default_collection_image/default_collection_img.jpg', storage=store.storage.OverwriteStorage(), upload_to=store.models.slug_path, verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(default='default_genre_image/default_genre_img.png', storage=store.storage.OverwriteStorage(), upload_to=store.models.slug_path, verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='locationevents',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=store.storage.OverwriteStorage(), upload_to=store.models.slug_path, verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='subcollections',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=store.storage.OverwriteStorage(), upload_to=store.models.slug_path, verbose_name='изображение'),
        ),
    ]
