# Generated by Django 4.0.4 on 2022-05-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_ageread_image_alter_book_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ageread',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='full_description',
            field=models.TextField(blank=True, default='', verbose_name='полное описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='original_title',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='оригинальное название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='время событий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationevents',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcollections',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='описание'),
            preserve_default=False,
        ),
    ]
