# Generated by Django 4.0.4 on 2022-06-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_ageread_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='main_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcomments', to='store.comment', verbose_name='главный комментарий'),
        ),
    ]
