# Generated by Django 4.0.4 on 2022-05-11 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('store', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='количество')),
                ('purchase_price', models.PositiveIntegerField(help_text='только в момент покупки', verbose_name='цена покупки')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.bookmodel', verbose_name='книга')),
            ],
            options={
                'verbose_name': 'позиция',
                'verbose_name_plural': 'позиции',
            },
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('favourites', models.ManyToManyField(blank=True, to='store.bookmodel', verbose_name='избранное')),
                ('positions', models.ManyToManyField(blank=True, to='customer.positionmodel', verbose_name='позиции')),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'корзины',
            },
        ),
        migrations.AddField(
            model_name='buymodel',
            name='positions',
            field=models.ManyToManyField(to='customer.positionmodel', verbose_name='позиции'),
        ),
        migrations.AddField(
            model_name='buymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
