# Generated by Django 4.0.4 on 2022-05-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_position_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='комментарий к заказу'),
            preserve_default=False,
        ),
    ]
