# Generated by Django 4.0.4 on 2022-05-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_ageread_description_and_more'),
        ('customer', '0006_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='cart_history', to='store.book', verbose_name='история'),
        ),
    ]
