# Generated by Django 4.0.4 on 2022-05-30 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_ageread_description_and_more'),
        ('customer', '0007_cart_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='history',
        ),
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.book', verbose_name='книга')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.cart', verbose_name='корзина')),
            ],
            options={
                'verbose_name': 'история просмотра',
                'verbose_name_plural': 'истории просмотров',
                'ordering': ['-date'],
            },
        ),
    ]
