# Generated by Django 4.0.4 on 2022-05-30 09:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_cart_history_browsinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsinghistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 9, 4, 29, 802411, tzinfo=utc), verbose_name='дата'),
        ),
    ]
