# Generated by Django 4.0.4 on 2022-05-30 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_browsinghistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsinghistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата'),
        ),
    ]
