# Generated by Django 4.0.4 on 2022-06-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_comment_main_comment'),
        ('customer', '0010_alter_browsinghistory_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='browsinghistory',
            unique_together={('book', 'cart')},
        ),
    ]
