# Generated by Django 4.0.4 on 2022-06-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_browsinghistory_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-date',), 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
