# Generated by Django 4.0.4 on 2022-06-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_processing', 'В обработке'), ('sent', 'Отправлен в пункт выдачи'), ('wait', 'Ожидает получения'), ('completed', 'Завершен'), ('cancel', 'Отменен')], default='in_processing', max_length=128, verbose_name='статус'),
        ),
    ]
